CREATE TABLE CHAUFFEUR
(
  CHAUFFEURCITY  VARCHAR2(20),
  CHAUFFEURSTATE VARCHAR2(20),
  CONSTRAINT Chauffeur_PK
    PRIMARY KEY(CHAUFFEURCITY)
);

CREATE TABLE RECORD
(
  RECORDNUMBER      NUMBER(20),
  LICENSENUMBER     NUMBER(20),
  RENEWED           DATE,
  STATUS            VARCHAR2(20),
  STATUSDATE        DATE,
  DRIVERTYPE        VARCHAR2(20),
  LICENSETYPE       VARCHAR2(20),
  ORIGINALISSUEDATE DATE,
  NAME              VARCHAR2(20),
  SEX               VARCHAR2(10),
  CHAUFFEURCITY     VARCHAR2(20),
  CONSTRAINT Record_PK
    PRIMARY KEY(RECORDNUMBER),
  CONSTRAINT Rrcord_FK
    FOREIGN KEY(CHAUFFEURCITY)
    REFERENCES CHAUFFEUR(CHAUFFEURCITY)
);