/* Assignment5 Part3-1 */
SELECT b.FNAME, b.MINIT, b.LNAME
FROM EMPLOYEE a, EMPLOYEE b
WHERE a.SSN = b.SUPER_SSN
AND a.FNAME = 'Franklin'
AND a.MINIT = 'T'
AND a.LNAME = 'Wong';

/* Part3-2 */
SELECT p.PNAME, p.PNUMBER, SUM(w.HOURS) AS TOTAL
FROM PROJECT p, WORKS_ON w
WHERE p.PNUMBER = w.PNO
GROUP BY p.PNAME, p.PNUMBER;

/* Part3-3 */
SELECT d.DNUMBER, d.DNAME, AVG(e.SALARY) AS AVERAGE
FROM DEPARTMENT d, EMPLOYEE e
WHERE d.DNUMBER = e.DNO
GROUP BY d.DNAME, d.DNUMBER
ORDER BY d.DNUMBER ASC;

/* Part3-4 */
SELECT AVG(SALARY) AS AVERAGE
FROM EMPLOYEE
WHERE SEX = 'F';

/* Part3-5 */
SELECT d.DNAME, COUNT(e.DNO) AS NOOFEMPLOYEE
FROM DEPARTMENT d, EMPLOYEE e
WHERE d.DNUMBER = e.DNO
GROUP BY d.DNAME
HAVING AVG(SALARY) > 43000;

/* Part3-6 */
SELECT FNAME, MINIT, LNAME
FROM EMPLOYEE
WHERE SALARY < (SELECT MAX(SALARY) FROM EMPLOYEE)
AND (SELECT MAX(SALARY) FROM EMPLOYEE) - SALARY <= 22000;
