/* Assignment5 Part1-1 */
SELECT ANIMAL.ANAME, HANDLES.ZOOKEEPID
FROM ANIMAL, HANDLES
WHERE ANIMAL.AID = HANDLES.ANIMALID;

/* Part1-2 */
SELECT ANIMAL.ANAME, HANDLES.ZOOKEEPID
FROM ANIMAL
LEFT JOIN HANDLES
ON ANIMAL.AID = HANDLES.ANIMALID;

/* Part1-3 */
SELECT ZOOKEEPER.ZNAME, SUM(ANIMAL.TIMETOFEED) AS TOTAL
FROM ZOOKEEPER, ANIMAL, HANDLES
WHERE ANIMAL.AID = HANDLES.ANIMALID
AND HANDLES.ZOOKEEPID = ZOOKEEPER.ZID
GROUP BY ZOOKEEPER.ZNAME;
                
/* Part1-4 */
SELECT HANDLES.ASSIGNED, ZOOKEEPER.ZNAME, ANIMAL.ANAME
FROM HANDLES, ZOOKEEPER, ANIMAL
WHERE HANDLES.ANIMALID = ANIMAL.AID
AND ZOOKEEPER.ZID = HANDLES.ZOOKEEPID
ORDER BY HANDLES.ASSIGNED ASC;

/* Part1-5 */
SELECT ANAME
FROM ANIMAL
WHERE AID IN (SELECT ANIMALID FROM HANDLES
              GROUP BY ANIMALID
              HAVING COUNT(ZOOKEEPID) >= 1);

/* Part1-6 */
SELECT ANAME
FROM ANIMAL
WHERE AID IN (SELECT ANIMALID FROM HANDLES
              GROUP BY ANIMALID
              HAVING COUNT(ZOOKEEPID) < 2);

/* Part1-Extra */
SELECT a.ANAME, a.TIMETOFEED, b.ANAME, b.TIMETOFEED
FROM ANIMAL a, ANIMAL b
WHERE a.TIMETOFEED > b.TIMETOFEED
AND a.TIMETOFEED - b.TIMETOFEED <= 0.25;