--------------------------------------------------------
--  File created - Saturday-April-09-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENTINFO
--------------------------------------------------------

  CREATE TABLE "YYANG97"."STUDENTINFO" 
   (	"FIRSTNAME" VARCHAR2(20 BYTE), 
	"LASTNAME" VARCHAR2(20 BYTE), 
	"GPA" VARCHAR2(20 BYTE), 
	"CREDITS" VARCHAR2(20 BYTE), 
	"ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table HONOR
--------------------------------------------------------

  CREATE TABLE "YYANG97"."HONOR" 
   (	"GPA" VARCHAR2(20 BYTE), 
	"HONOR" VARCHAR2(20 BYTE), 
	"ID" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into YYANG97.STUDENTINFO
SET DEFINE OFF;
Insert into YYANG97.STUDENTINFO (FIRSTNAME,LASTNAME,GPA,CREDITS,ID) values ('Fab','Lab','3.2','80',1);
Insert into YYANG97.STUDENTINFO (FIRSTNAME,LASTNAME,GPA,CREDITS,ID) values ('Fcd','Lcd','2.8','70',2);
Insert into YYANG97.STUDENTINFO (FIRSTNAME,LASTNAME,GPA,CREDITS,ID) values ('Fbc','Lbc','3.5','90',3);
Insert into YYANG97.STUDENTINFO (FIRSTNAME,LASTNAME,GPA,CREDITS,ID) values ('Fde','Lde','3','100',4);
Insert into YYANG97.STUDENTINFO (FIRSTNAME,LASTNAME,GPA,CREDITS,ID) values ('Fef','Lef','2.7','75',5);
REM INSERTING into YYANG97.HONOR
SET DEFINE OFF;
Insert into YYANG97.HONOR (GPA,HONOR,ID) values ('3.2','YES',1);
Insert into YYANG97.HONOR (GPA,HONOR,ID) values ('2.8','NO',2);
Insert into YYANG97.HONOR (GPA,HONOR,ID) values ('3.5','YES',3);
Insert into YYANG97.HONOR (GPA,HONOR,ID) values ('3','YES',4);
Insert into YYANG97.HONOR (GPA,HONOR,ID) values ('2.7','NO',5);
--------------------------------------------------------
--  DDL for Index STUDENTINFO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YYANG97"."STUDENTINFO_PK" ON "YYANG97"."STUDENTINFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index HONOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "YYANG97"."HONOR_PK" ON "YYANG97"."HONOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STUDENTINFO
--------------------------------------------------------

  ALTER TABLE "YYANG97"."STUDENTINFO" ADD CONSTRAINT "STUDENTINFO_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "YYANG97"."STUDENTINFO" MODIFY ("FIRSTNAME" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."STUDENTINFO" MODIFY ("LASTNAME" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."STUDENTINFO" MODIFY ("GPA" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."STUDENTINFO" MODIFY ("CREDITS" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."STUDENTINFO" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HONOR
--------------------------------------------------------

  ALTER TABLE "YYANG97"."HONOR" ADD CONSTRAINT "HONOR_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "YYANG97"."HONOR" MODIFY ("GPA" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."HONOR" MODIFY ("HONOR" NOT NULL ENABLE);
  ALTER TABLE "YYANG97"."HONOR" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table HONOR
--------------------------------------------------------

  ALTER TABLE "YYANG97"."HONOR" ADD CONSTRAINT "HONOR_FK1" FOREIGN KEY ("ID")
	  REFERENCES "YYANG97"."STUDENTINFO" ("ID") ENABLE;
