/* Assignment 4 */
/* Part3-1 */
SELECT ANAME
FROM ANIMAL
WHERE TIMETOFEED < 1.5;

/* Part3-2 */
SELECT ANAME, TIMETOFEED
FROM ANIMAL
WHERE ACATEGORY = 'rare'
ORDER BY TIMETOFEED ASC;

/* Part3-3 */
SELECT ANAME, ACATEGORY
FROM ANIMAL
WHERE ANAME LIKE '%bear';

/* Part3-4 */
SELECT ANAME, ACATEGORY
FROM ANIMAL
WHERE ACATEGORY IS NULL;

/* Part3-5 */
SELECT ANAME, ACATEGORY
FROM ANIMAL
WHERE TIMETOFEED <= 2.5
AND TIMETOFEED >= 1;

/* Part3-6 */
SELECT ANAME, ACATEGORY
FROM ANIMAL
WHERE ANAME LIKE '%tiger'
AND ACATEGORY <> 'common';

/* Part3-7 */
SELECT MAX(TIMETOFEED) AS MaxTime, MIN(TIMETOFEED) AS MinTime
FROM ANIMAL;

/* Part3-8 */
SELECT AVG(TIMETOFEED) AS AvgTime
FROM ANIMAL
WHERE ACATEGORY LIKE 'rare';

/* Part3-9 */
SELECT AID, ANAME, TIMETOFEED
FROM ANIMAL
WHERE AID < 10
AND TIMETOFEED > 2;