/*Assignment 3 Part 2 a*/
SELECT ID, LASTNAME, FIRSTNAME, ISBN
FROM AUTHORS, WRITE
WHERE AUTHORS.ID = WRITE.AUTHORID
ORDER BY LASTNAME ASC;
/*Assignment 3 Part 2 b*/
SELECT NAME, ADDRESS, TITLE, ISBN
FROM PUBLISHERS, BOOKS
WHERE BOOKS.PUBLISHERID = PUBLISHERS.ID
AND TITLE LIKE 'D%'
ORDER BY TITLE ASC;
/*Assignment 3 Part 3 c*/
SELECT *
FROM OFFICEINFO, BUILDINGINFO
WHERE OFFICEINFO.BUILDING = BUILDINGINFO.BUILDING
AND CITY LIKE 'C%';
/*Assignment 3 Part 3 d*/
SELECT MAIN.OFFICE, FLOOR, CITY, EXECUTIVE
FROM MAIN, OFFICEINFO, BUILDINGINFO, CLIENTINFO
WHERE MAIN.CLIENT = CLIENTINFO.CLIENT
AND MAIN.OFFICE = OFFICEINFO.OFFICE
AND OFFICEINFO.BUILDING = BUILDINGINFO.BUILDING
AND MDATE > '15/JAN/2014'
ORDER BY EXECUTIVE ASC;